import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "./globals.css";
import Header from "./PageComponents/Header/Header";
import Footer from "./PageComponents/Footer/Footer";
import "animate.css";
const sen = Sen({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sen.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
